### ISSUE TITLE
ATDIS - No data received

### ISSUE THREAD

**Issue by LoveMyData** [planningalerts-scrapers/yass#1]
Hi Yass council

I was looking at a progress of an application however the link seems no longer working.

I was at the main council web site http://www.yassvalley.nsw.gov.au/  then I click on the link say Track My DA on the right hand side then it is just thinking... thinking and more thinking.

Can you please investigate?

Many Thanks
Eric

**Comment by LoveMyData** [comment]
Thank you for your email to Yass Valley Council.  It will be referred to the appropriate Council Officer for his/her attention.
Please do not reply to this email as it has been electronically generated.

Yass Valley Council
PH: +61 (0)2 6226 1477

**Comment by CloCkWeRX** [comment]
Might be worth flicking the support team at solorient an email; though the Yass folks might have done that - the team there are pretty responsive :)

**Comment by CloCkWeRX** [comment]
http://mycouncil.yass.nsw.gov.au/Horizon/logonGuest.aw?domain=horizondap doesn't even resolve at the moment, sigh

**Comment by LoveMyData** [comment]
Looks like it is back online... so unstable
